name: AddonTemplate
author: Seggan
description: Addon Template
main: io.github.seggan.addontemplate.AddonTemplate
website: https://github.com/Seggan/AddonTemplate
depend: [Slimefun]
version: ${project.version}
api-version: 1.16

commands:
  addontemplate:
    description: Do /addontemplate help for a list of commands
    usage: /addontemplate <subcommand>
    aliases: [at]
